name: minimist
description: A Dart library for parsing command ling options and arguments inspired from minimist npm package.wh
version: 0.1.1
homepage: https://github.com/Clique-Paris/minimist

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
